---

  - name: Add Kibana yum repository
    template:
        dest: "{{ yum_repo_des }}" # required. Location to render the template to on the remote machine.
        src: "{{ yum_repo_file }}" # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.
        owner: root # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
        group: root # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
        backup: no # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
    when: kibana_repo

  - name: Add the kibana yum repository with yum repo
    yum_repository:
        name: "{{ kiabana_yum_file_name }}" # required. Unique repository ID. This option builds the section name of the repository in the repo file.,This parameter is only required if I(state) is set to C(present) or C(absent).
        enabled: yes # not required. This tells yum whether or not use this repository.
        owner: root # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
        repo_gpgcheck: no # not required. This tells yum whether or not it should perform a GPG signature check on the repodata from this repository.
        gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch" # not required. A URL pointing to the ASCII-armored GPG key file for the repository.,It can also be a list of multiple URLs.
        state: present # not required. choices: absent;present. State of the repo file.
        gpgcheck: "yes"
        description: "Elasticsearch Repository"
        baseurl: "https://artifacts.elastic.co/packages/7.x/yum"
        group: "root"
        async: yes # not required. If set to C(yes) Yum will download packages and metadata from this repo in parallel, if possible.
    when: kibana_yum_repo

  - name: Install kibana
    yum:
      name: { kibana_rpm }
      state: installed
    notify: start and enable kibana
    #when: yum_repository.success or template.success