---
# tasks file for automate_kibana

  - name: install Kibana
    include_tasks: install.yml
    when: kibana_install
    tag: install

  - name: Configure Kibana
    include_tasks: configure.yml
    when: kibana_install
    tag: configure